services:
  app:
    build:
      context: .
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY:-docker.m.daocloud.io}
    ports:
      - "${APP_PORT:-8081}:80"
    env_file:
      - backend/.env
    restart: unless-stopped
